src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderManagement.cls
public class OrderManagement {
	@AuraEnabled
	public static Account getAccount(string accid){
		return [SELECT id, name, accountnumber FROM Account WHERE id=:accid ];
	}

	@AuraEnabled
	public static User getUserSettings(){
		User user = new User();
		user = [SELECT Id, Name, IsManager__c  FROM User WHERE Id = : UserInfo.getUserId()];
		return user;
	}

	@AuraEnabled
	public static List<Product__c> addtoCart(string productid, List<Product__c> cart){
		Product__c prd = new Product__c();
		prd = [SELECT id, name, Description__c, Price__c, Type__c, Family__c FROM Product__c WHERE id=:productid ];
		List<Product__c> updlist = cart;
		updlist.add(prd);
		return updlist;
	}

	@AuraEnabled
	public static Decimal countTotalSum (List<Product__c> productList){

		Decimal totalsum = 0;
		for (Product__c prd : productList){
			totalSum += prd.Price__c;
		}
		return totalSum;
	}


	@AuraEnabled
	public static Integer countTotalQuantity (List<Product__c> productList){
		return productList.size();
	}


	@AuraEnabled
	public static void CreateOrder(List<Product__c> productList, string accountId) {
		System.Debug('CreateOrderStart');

		Order__c order = new Order__c();
		order.AccountId__c = accountId;
		insert order;
		System.Debug('OrderInserted');

		Order__c orderid = [select id from Order__c WHERE TotalProductCount__c = null];
		List<OrderItem__c> orderItems = new List<OrderItem__c>();
		System.Debug('OrderITemsListCreated');

		for (Product__c prd : productList) {

			OrderItem__c orderItem = new OrderItem__c();
			System.Debug('OrderItem created');

			orderItem.OrderId__c = orderid.Id;
			orderItem.ProductId__c = prd.Id;
			orderItem.Price__c = prd.Price__c;
			orderItem.Quantity__c = 1;

			orderItems.add(orderItem);
			System.Debug('Add item to list');
		}

		insert orderItems;
		update order;
		System.Debug('Insert');
	}

}