src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderManagementTest.cls
@IsTest
public class OrderManagementTest {
	@IsTest static void testTotalQuantity(){
		List<Product__c> temp = new List<Product__c>
				{
				new Product__c(Name='Product1',Price__c = 100, Type__c ='Type1', Family__c = 'Family1'),
				new Product__c(Name='Product2',Price__c = 500, Type__c ='Type2', Family__c = 'Family5'),
				new Product__c(Name='Product3',Price__c = 300, Type__c ='Type3', Family__c = 'Family5')
				};
		integer count = OrderManagement.countTotalQuantity(temp);
		System.assertEquals(3,count);
	}

	@IsTest static void testTotalSum(){
		List<Product__c> temp = new List<Product__c>
				{
				new Product__c(Name='Test1',Price__c = 100, Type__c ='Type1', Family__c = 'Family1'),
				new Product__c(Name='Test2',Price__c = 500, Type__c ='Type2', Family__c = 'Family5'),
				new Product__c(Name='Test3',Price__c = 300, Type__c ='Type3', Family__c = 'Family5')
				};
		decimal sum = OrderManagement.countTotalSum(temp);
		System.assertEquals(900,sum);
	}

	@IsTest static void getUserSettingsTest(){
		User usrexpected = [SELECT Id, Name, IsManager__c  FROM User WHERE Id = : UserInfo.getUserId()];
		User user = OrderManagement.getUserSettings();

		System.assertEquals(usrexpected,user);
	}

	@IsTest static void CreateOrderTriggerTest(){
		List<Product__c> prdList = new List<Product__c>
				{
				new Product__c(Name='Test1',Price__c = 100, Type__c ='Type1', Family__c = 'Family1'),
				new Product__c(Name='Test2',Price__c = 500, Type__c ='Type2', Family__c = 'Family5'),
				new Product__c(Name='Test3',Price__c = 300, Type__c ='Type3', Family__c = 'Family5')
				};
		OrderManagement.CreateOrder(prdList, '0015I000002mbv7QAA');
		Order__c result = [select TotalProductCount__c, totalprice__c from order__c where accountid__c = '0015I000002mbv7QAA' ];

		System.assertEquals(3, result.TotalProductCount__c);
		System.assertEquals(900, result.totalprice__c);

	}

	@IsTest static void CreateOrderTest(){
		List<Product__c> prdList = new List<Product__c>
				{
				new Product__c(Name='Test1',Price__c = 100, Type__c ='Type1', Family__c = 'Family1'),
				new Product__c(Name='Test2',Price__c = 500, Type__c ='Type2', Family__c = 'Family5'),
				new Product__c(Name='Test3',Price__c = 300, Type__c ='Type3', Family__c = 'Family5')
				};
		OrderManagement.CreateOrder(prdList, '0015I000002mbv7QAA');

		List<Orderitem__c> orderItem = [select id from orderitem__c];


		System.assertEquals(prdList.size(), orderItem.size());

	}

	@IsTest static void CreateOrderItemTest(){
		List<Product__c> prdList = new List<Product__c>
				{
				new Product__c(Name='Test1',Price__c = 100, Type__c ='Type1', Family__c = 'Family1'),
				new Product__c(Name='Test2',Price__c = 500, Type__c ='Type2', Family__c = 'Family5'),
				new Product__c(Name='Test3',Price__c = 300, Type__c ='Type3', Family__c = 'Family5'),
				new Product__c(Name='Test4',Price__c = 300, Type__c ='Type3', Family__c = 'Family5')
				};
		OrderManagement.CreateOrder(prdList, '0015I000002mbv7QAA');

		Order__c order = [select id from order__c];
		id orderid = order.Id;
		List<Orderitem__c> orderItem = [select id from orderitem__c where orderid__c =: orderid ];


		System.assertEquals(4, orderItem.size());


	}

}