src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/searchProductController.cls
public class searchProductController {    
    @AuraEnabled
    public static List <Product__c> fetchAllProduct() {
        List <Product__c> returnList = new List <Product__c> ();
        List <Product__c> lstOfProduct = [select id, Name, Description__c, Type__c, Family__c, Price__c from Product__c];
        
        for (Product__c prd: lstOfProduct) {
            returnList.add(prd);
        }
        return returnList;
    }
    @AuraEnabled
    public static Product__c saveProduct(Product__c product) {
        upsert product;
        return product;
    }
    
    @AuraEnabled
    public static List <Product__c> filterProduct(String searchKeyWord, string ntype, string nfamily) {
        
        if(ntype==null)
            ntype='';
        if(nfamily==null)
            ntype='';
        if(searchKeyWord==null)
            searchKeyWord='';
        
        String typeKey = '%' + ntype + '%';
        String familyKey = '%' + nfamily + '%';
        String searchKey = '%' + searchKeyWord + '%';
        List <Product__c> returnList = new List <Product__c> ();
        List <Product__c> lstOfProduct = [select id, Name, Description__c, Price__c from Product__c where Name LIKE: searchKey and Type__c LIKE: typeKey and Family__c LIKE: familyKey];
        
        for (Product__c prd: lstOfProduct) {
            returnList.add(prd);
        }
        return returnList;
    }
    @AuraEnabled
    public static List<String> fetchProductTypes(List<Product__c> productList){
        
        Set<String> temp = new Set<String>();
        String[]types = new String[]{};
            
            for (Product__c t : productList){
                temp.add(t.Type__c);
            }
        types.addAll(temp);
        
        return types;
    }

    
    @AuraEnabled
    public static List<String> fetchProductFamilies(List<Product__c> productList){
        
        Set<String> temp = new Set<String>();
        String[]families = new String[]{};
            
            for (Product__c t : productList){
                temp.add(t.Family__c);
            }
        families.addAll(temp);
        
        return families;
    }
}